### ISSUE TITLE
MediaProviderInterface not found

### ISSUE THREAD

**Issue by malekhaouari** [ghaliano/AwesomeMedia#6] opened 2016-04-07 17:12 UTC
PHP Fatal error:  Interface 'MediaGateway\MediaProviderInterface' not found in /var/www/html/inscreen/vendor/ghaliano/media-gateway/MediaGa  
  teway/src/MediaGateway/Provider/ProviderChain.php on line 9

**Comment by ghaliano** [comment] 2016-04-07 17:31
Try with composer dump-autoload

**Comment by malekhaouari** [comment] 2016-04-08 08:40
I did compose dump-autoload, always the same mistakes

**Comment by malekhaouari** [comment] 2016-04-08 14:51
my class is as follows:

namespace InScreen \ CoreBundle \ Media;

use InScreen \ CoreBundle \ Media \ Search \ MediaSearchFactory;
use JMS \ DiExtraBundle \ Annotation as DI;
use MediaGateway \ Provider \ ProviderChain have BaseMediaAggregator;

/ *\* @DI \ Service ("media.aggregator") \* /
MediaAggregator class extends BaseMediaAggregator
{
}

the problem is in: use MediaGateway \ Provider \ ProviderChain have BaseMediaAggregator;

the class path is invalid, the class is in vendor, the solution I did is to overload the records of vendor, now it works well, can we avoid overloading ??

**Comment by ghaliano** [comment] 2016-05-24 17:11
i am closing this issue because any testable reproduction was given

**Comment by ghaliano** [comment] 2016-05-24 17:12
i am closing this issue because any testable reproduction was given.

**Closed as completed by ghaliano** 2016-05-24 17:12 UTC
